#this script takes the file generated by Manhattan_all_pheno.R and filters it for bonferroni significance, generates a [model]_bonferroni_all_pheno.csv file
library(dplyr)
library(data.table)
"%&%" = function(a,b) paste(a,b,sep="")

#models<-c("INTERVAL","TOPMedPAVrho","TOPMedrho")
#for (model in models){
	spred<-read.csv("FUSIONPWAS_all_pheno.csv")
#	bonf <- 0.05/(7*nrow(spred))
	bonf<-5.6e-06
	signif <- filter(spred,-log10(P) > -log10(bonf))
	#print(model)
	print(nrow(spred))
	print(bonf)
	signif <- unique(signif)  
	write.csv(signif,file="FUSION_PWAS_5.6e-06_all_pheno.csv",quote=F,row.names=F)
#}
