#this script takes the file generated by Manhattan_all_pheno.R and filters it for bonferroni significance, generates a [model]_bonferroni_all_pheno.csv file
library(dplyr)
library(data.table)
"%&%" = function(a,b) paste(a,b,sep="")

#models<-c("INTERVAL","TOPMedPAVrho","TOPMedrho")
#for (model in models){
	spred<-fread("Cancer_PrediXcan_with_FDR.txt",stringsAsFactors=F)
#	bonf <- 0.05/(7*nrow(spred))
	bonf<-.05
	signif <- filter(spred,-log10(ARIC_fdr_pvalue) > -log10(bonf))
	#print(model)
#	print(nrow(spred))
#	print(bonf)
	signif <- unique(signif)  
	fwrite(signif,file="Cancer_PrediXcan_FDR_sig.txt",sep="\t",quote=F,row.names=F)
#}
